#ifndef UDIF_RESOURCES_H
#define UDIF_RESOURCES_H

/**
* \file resources.h
* \brief The UDIF common resources
*/

#define UDIF_APPLICATION_MESSAGE_STRING_DEPTH 167U
#define UDIF_APPLICATION_MESSAGE_STRING_SIZE 128U
#define UDIF_APPLICATION_COMMAND_STRING_DEPTH 10U
#define UDIF_APPLICATION_COMMAND_STRING_SIZE 64U
#define UDIF_APPLICATION_CONSOLE_MODE_STRING_DEPTH 14U
#define UDIF_APPLICATION_CONSOLE_MODE_STRING_SIZE 23U
#define UDIF_APPLICATION_HELP_STRING_DEPTH 48U
#define UDIF_APPLICATION_HELP_STRING_SIZE 128U

static const char UDIF_APPLICATION_MESSAGE_STRINGS[UDIF_APPLICATION_MESSAGE_STRING_DEPTH][UDIF_APPLICATION_MESSAGE_STRING_SIZE] =
{
	"The command was not recognized.",
	"The system will be erased, including configuration and log files, do you want to proceed Y | N",
	"The user configuration will be erased, do you want to proceed Y | N",
	"The log files will be erased, do you want to proceed Y | N",
	"The user is not authorized. Press any key to terminate the application.",
	"Login has exceeded maximum retries. Press any key to terminate the application.",
	"The quit command has been entered. Press any key to terminate the application.",
	"Activity logging has been disabled.",
	"Activity logging has been enabled.",
	"User authentication has failed. Press any key to terminate the application.",
	"The operation was aborted by the user.",
	"System reset : The application log and configuration have been erased.",
	"System reset : The application log and configuration have been erased.",
	"The log file has been erased.",
	"The retry setting is invaid; valid retry range is between one and five[1-5] login attempts.",
	"The timeout setting is invalid; valid timeout setting is between one and sixty[1-60] minutes.",
	"The domain name setting is invalid; valid domain name length is between two and thirty[2-32] characters.",
	"The hostname setting is invalid; valid hostname length is between two and thirty[2-32] characters.",
	"Printing configuration details : ",
	"Printing connection details : ",
	" minutes",
	"The log file is empty.",
	"Running for the first time; please set the applications device name, username and password.",
	"Please choose a user name, minimum 6 characters, to a maximum 128 characters.",
	"Password must be 8-128 characters long[a-z, A-Z], at least 1 number, and 1 symbol[0-9][!#$ & '()*+,_./].",
	"The user name and password have been set.",
	"Please enter the user name : ",
	"The user name entered is not recognized.",
	"Please enter the password : ",
	"The password entered is invalid.",
	"Please enter the device name, minimum 2 characters, to a maximum of 16 characters",
	"The device name has been set.",
	"The device name is invalid.",
	"Enter the IPv4 or IPv6 address of the host name.",
	"No public key is associated with that address.Enter the encoded public key.",
	"Connecting to the server...",
	"Connection attempt failed! The server is unreachable.",
	"The host has entered server mode. Type quit to exit server mode.",
	"The listener failed to initialize. The host could not enter the listening state.",
	"The listener has initialized : The server is now in the listening state.",
	"Generating the public/private signature key-pair.",
	"The certificate could not be generated.",
	"The public key was saved to: ",
	"The signature key-pair already exists, do you want to overwite it ? Y | N",
	"The operation was cancelled by the user.",
	"Enter the path to the remote hosts public key.",
	"Invalid path, could not find the hosts public key.",
	"Client disconnected from the remote host successfully.",
	"Connection attempt failed! Could not connect to the remote server.",
	"The IP address format was invalid! Enter a valid address format, ex.n.n.n.n",
	"Warning! The local certificate exists, do you want to overwite it ? Y | N",
	"Cannot delete an active certificate; revoke the certificate before deleting the file.",
	"The console timeout period has expired, set to user mode.",
	"Enter the full path to the ARS root certificate.",
	"The root certificate has been stored successfully.",
	"Could not find the certificate, or the file is invalid, please enter the path again.",
	"The root certificate has been copied successfully.",
	"The root certificate could not be copied, check the path and permissions.",
	"The certificate signing failed. File permissions, the certificate is invalid, or has incompatible parameters.",
	"The certificate was signed successfully.",
	"The command input was invalid, operation failed.",
	"The network join request has failed, check the address.",
	"The network join request has succeeded.",
	"The node is joined to an existing network, rejoin the ads ? Y | N",
	"The certificate announce operation has failed, check the path.",
	"The certificate has been announced to the network.",
	"The topology convergence has been processed by the network.",
	"The topology update has failed, memory or signing failure.",
	"The network time is invalid or has substantial delay.",
	"The root, ads, or aps certificate could not be found.",
	"The signature could not be generated for a message.",
	"The network resign has failed, check the address.",
	"This node has resigned from the network.",
	"The certificate revocation has failed, check the path.",
	"The certificate revocation has been broadcast to the network.",
	"The address is not routable, or not properly formed.",
	"The server ip address has been changed, restart the server for changes to take effect.",
	"Do you want to change the ip address ? Y | N",
	"The auto-detected ip address is : ",
	"Enter a routable IPv4 or IPv6 address.",
	"The server service could not be started, check for a valid signed certificate and network membership.",
	"The server service was started successfully.",
	"The server service has been stopped, use the command 'service start' to run.",
	"The server service has been paused, use the command 'service resume' to restart.",
	"The server service could not be resumed, use the command 'service start' to run.",
	"The server service has resumed successfully.",
	"The server certificate already exists, do you want to replace it ? Y | N",
	"Changing the server name or the domain name requires recreating the certificate, do you want to proceed ? Y | N",
	"The server certificate could not be updated, check the path and root signature",
	"The server certificate was updated successfully",
	"The server certificate could not be exported, check the path",
	"The server certificate was exported successfully",
	"Do you want to change the servers domain name ? Y | N",
	"The current domain name string : ",
	"The server could not update the domain name.",
	"The domain name has been updated successfully.",
	"The days entered exceeds the root expiration period; days reduced to: ",
	"The certificate must be signed by the ARS server before joining the network.",
	"The command is not supported on this server or version.",
	"The network address is invalid or not set.",
	"Received a network error from remote host : ",
	"A network error occured with remote host : ",
	"The query name format is invalid, use the remote device name, ex. MAS1",
	"The device is offline or unknown to the ADC",
	"The device is online and available for connection",
	"The certificate was not found or is not signed.",
	"Provide the full path to the signed ADC certificate.",
	"Provide the IP address of the ADC server.",
	"The ADC IP address format is invalid.",
	"Restore the configuration files from the last backup?",
	"The configuration files have been backed up.",
	"The proxy service could not sign the certificate.",
	"The certificate was signed by the proxy service.",
	" - The server address has been changed by the administrator ",
	" - The domain name was changed to ",
	" - The host name was changed to ",
	" - Local user logged in: ",
	" - Log file created: ",
	" - Logging has been disabled on ",
	" - Logging has been enabled on ",
	"UDIF version 1.0.0.0a, created September 2025.",
	" - The login retries setting was changed to ",
	" - The session timeout was changed to ",
	" - Added user configuration: ",
	" - The server state has been restored ",
	" - The server state has been backed up ",
	" - The server service was paused ",
	" - The server service was resumed ",
	" - The server service was started ",
	" - The server service was stopped ",
	" - The network mfk exchange has failed ",
	" - The network mfk exchange has succeeded ",
	" - The server generated a replacement certificate: ",
	" - The certificate generation has failed. ",
	" - The certificate generation has succeeded: ",
	" - The certificate announcement has succeeded ",
	" - The certificate revocation has failed ",
	" - The converce call has returned a failure ",
	" - The remote host has converged and updated its certificate ",
	" - The topological update request failed or was denied ",
	" - The topological update request was sent ",
	" - Memory allocation failure, connection aborted to host ",
	" - Connection terminated by remote host ",
	" - The configuration was erased by user: ",
	" - The network session has timed out ",
	" - The network ads join request was denied ",
	" - The network ads join request has succeeded ",
	" - The key fragment exchange has failed ",
	" - The key fragment exchange has succeeded ",
	" - The host resignation from the network failed ",
	" - The host has resigned from the network ",
	" - The remote device sent an invalid or unknown request ",
	" - The remote device responded with an error code ",
	" - Remote connection failed at ",
	" - Connected to remote host: ",
	" - The node query failed ",
	" - The device answered a node query successfully ",
	" - The node was not found in the topological database ",
	" - The certificate announcement has failed ",
	" - The remote certificate could not be signed ",
	" - The remote certificate was signed successfully ",
	" - The remote host resignation from the network failed ",
	" - The remote host has resigned from the network ",
	"Do you want to revoke this device and remove it from the database?",
	"Provide the IP address of the ARS server.",
	"The ARS IP address format is invalid.",
	"The server service must be started before issuing this command."
};

static const char UDIF_APPLICATION_HELP_STRINGS[UDIF_APPLICATION_HELP_STRING_DEPTH][UDIF_APPLICATION_HELP_STRING_SIZE] =
{
	"unknown command",
	/* configuration commands */
	"address[ip-address] -Assign the server's network interface address; requires a restart.",
	"certificate -enter the certificate command interface",
	"clear all -requires auth challenge, deletes everything",
	"clear config -requires auth challenge, deletes public key cache",
	"clear log -requires auth challenge, clears the logs",
	"exit -exits to enable mode",
	"help -config mode command help",
	"log - [enable | disable] log command and connection activity",
	"name domain[domain-name] -fully qualified domain -name",
	"name host[host-name]",
	"retries[count] -authentication retries, default is 2",
	"server -enter server configuration mode",
	"timeout[seconds] -session default 120",
	/* enable commands */
	"clear screen -clear the screen",
	"config -enter configuration mode",
	"exit -exits to user mode",
	"help -enable mode command help",
	"quit -closes the application",
	"show config -show configuration",
	"show log -show the user activity log",
	/* user commands */
	"enable -triggers authentication challenge",
	"help -user mode command help",
	"quit -closes the application",
	/* config-certificate commands */
	"exit -exits to config mode",
	"export[certificate-directory] -exports the local certificate to a file",
	"generate[period-days] -generate the public certificate",
	"help -certificate mode command help",
	"import[certificate-path] -imports a certificate from a file",
	"print -print a certificate",
	/* config-server commands */
	"backup -save a backup of the aps state",
	"connect [canonical-name] -connects to an application server or client",
	"exit -exits to config mode",
	"help -server mode command help",
	"list -display the topological database",
	"register [ip-address] -register aps with the ADC",
	"resign [ip-address] -resign from the ADC",
	"restore -restore the device state from backup",
	"service -[start|stop|pause|resume] the server service",
	/* client config-connect commands */
	"query [canonical-name] -Request node information for a device from the ADC",
	"help -connect mode command help",
	"quit -quits the remote server connection",
	/* ads config-certificate commands */
	"revoke [certificate-path] -revoke the local device certificate",
	/* ads config-server commands */
	"announce [certificate-path, ip-address] -announce an aps to servers in the network",
	"converge -announce a topology update to the network",
	"revoke [certificate-path] -revoke an aps's credentials by announcing it to the network",
	"sproxy [certificate-path] -send a remote certificate signing request to the ARS server",
	/* rds config-certificate commands */
	"sign [certificate-path] -sign a child certificate"
};

static const char UDIF_APPLICATION_MODE_STRINGS[UDIF_APPLICATION_CONSOLE_MODE_STRING_DEPTH][UDIF_APPLICATION_CONSOLE_MODE_STRING_SIZE] =
{
	"UDIF",
	"> ",
	"# ",
	"(config)# ",
	"(config-certificate)# ",
	"(config-server)# ",
	"(login-message)> ",
	"(login-password)> ",
	"(login-username)> ",
	"(login-devicename)> ",
	"(login-address)> ",
	"(login-domain)> ",
	"(login-rootpath)> ",
	"(server-connected)# "
};

#endif
